apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jdc3wbvar-python 
  janus-idp.io/tekton: jdc3wbvar-python
  backstage.io/kubernetes-id: jdc3wbvar-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jdc3wbvar-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml